### ISSUE TITLE
griddler-cloudmailin gem cannot be released by current project maintainer

### ISSUE THREAD

**Issue by dominicsayers** [thoughtbot/griddler-cloudmailin#10]
The `griddler-cloudmailin` gem is owned by @melvinxie and authored by @calebthompson. It is currently stuck on the initial release, although the codebase has moved on significantly.

Please can @scsmith be given access to release a new version of the gem?

**Comment by dominicsayers** [comment]
Bump

**Comment by dominicsayers** [comment]
Bumpity bump

**Comment by dominicsayers** [comment]
We may have to release the gem under a different name to bypass the unresponsiveness of the current gem owner.

**Comment by calebhearth** [comment]
Only @melvinxie (or melvinxie@gmail.com at any rate) has ownership of the Ruby gem. I guess I removed myself at some point. I'm unsubscribing from this thread, but good luck!

**Comment by melvinxie** [comment]
Sorry for late response. I added dominicsayers as the gem owner now.

**Comment by dominicsayers** [comment]
Thanks @melvinxie 🥇
