### ISSUE TITLE
Consider moving to the normalized format

### ISSUE THREAD

**Issue by scsmith** [thoughtbot/griddler-cloudmailin#13]
The normalized format was added to CloudMailin to make applications like griddler slightly easier. The format makes sure that all headers are lower-cased and deals with arrays in a more generic way.

It might be worth updating the gem to follow these practices as it will make sure less oddities like `envelope['To']`.

Thoughts?

**Comment by dominicsayers** [comment]
Is there some documentation of this format on the Cloudmailin site?

**Comment by scsmith** [comment]
Not yet, but there needs to be. I'll look at getting this sorted ASAP.

**Comment by dominicsayers** [comment]
Can you review [PR#20](https://github.com/thoughtbot/griddler-cloudmailin/pull/20) to check I've got it right?

**Comment by dominicsayers** [comment]
@scsmith Now we can release the gem to Rubygems, I'd like to get this merged
