### ISSUE TITLE
Add test coverage checks

### ISSUE THREAD

**Issue by dominicsayers** [thoughtbot/griddler-cloudmailin#14]
Add Coveralls so we can show that test coverage is adequate.

@scsmith: We need to add this project to Travis or CircleCI in order to get a Coveralls reading. I can't do this because I'm not an admin. Please can you configure Travis or CircleCI to build this project?

**Comment by scsmith** [comment]
Any preference as to which? We use both but I think travis is probably easier for open source projects, is that ok?

**Comment by dominicsayers** [comment]
Perfect
