### ISSUE TITLE
Complete hakiri integration

### ISSUE THREAD

**Issue by dominicsayers** [thoughtbot/griddler-cloudmailin#15]
No biggie, but the Hakiri integration isn't completely set up. I think it might be because I'm not an admin of this Github project.

Could you try clicking the `Recreate` button on this page? https://hakiri.io/projects/305dadd393efb1/integrations

**Comment by scsmith** [comment]
I get a 404 error message when trying to set things up. However, it does appear to be working:

[![security](https://hakiri.io/github/thoughtbot/griddler-cloudmailin/master.svg)](https://hakiri.io/github/thoughtbot/griddler-cloudmailin/master)

```
[![security](https://hakiri.io/github/thoughtbot/griddler-cloudmailin/master.svg)](https://hakiri.io/github/thoughtbot/griddler-cloudmailin/master)
```

**Comment by dominicsayers** [comment]
Awesome. I got the URL wrong in the README so I'll fix that and we should be good.
