### ISSUE TITLE
Remove unnecessary dependency on mime-types

### ISSUE THREAD

**Issue by dominicsayers** [thoughtbot/griddler-cloudmailin#18]
The gemspec currently restricts the version of `mime-types` to `< 3.0` because `mime-types` only supports Ruby 2+ since v3.0.

`mime-types` has already released v3.1 and Ruby 1.9.x is no longer maintained.

It seems perverse to artificially restrict the `mime-types` version simply to support an unsupported Ruby. It will lead to problems when users of this gem also rely on features of `mime-types` introduced since v3.0.

**Comment by scsmith** [comment]
Quite a few gems are doing things like:

```ruby
gem "mime-types", (RUBY_VERSION >= "2.0" ? "~> 3.0" : "~> 2.99")
```

Unless we're fully dropping 1.9 support I do think it will be possible to resolve things depending on Ruby version. I'm not fully against dropping 1.9 just wondering if this is an option?

**Comment by dominicsayers** [comment]
Here's a thing. I can't see where this gem is used in the code. It's never required and the specs pass without it being in the gemspec.

I guess Caleb added it to the gemspec in the early days.

**Comment by scsmith** [comment]
It looks liked it was added in 95509967aee8b3dca2f063226697139a37381f85. I know that commit was cleaned up and went through a few iterations etc. Maybe it wasn't needed after all?

Looks like a pretty easy solution for now though :-)

**Comment by dominicsayers** [comment]
Nobody to blame but me then 🤦‍♂️ 

I'll remove it.
