### ISSUE TITLE
Coveralls doesn't work under jruby

### ISSUE THREAD

**Issue by dominicsayers** [thoughtbot/griddler-cloudmailin#21]
The jruby tests on Travis pass OK, but the Coveralls figure is 0%. This leads to the aggregated Coveralls figure being lower than it should be.

See the log here: https://travis-ci.org/thoughtbot/griddler-cloudmailin/jobs/212176748

**Comment by stefannibrasil** [comment]
This library has been deprecated: https://github.com/thoughtbot/griddler-cloudmailin/pull/23
