### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by gabebw** [thoughtbot/griddler-cloudmailin#8]
This adapter has languished and deserves a new maintainer.

If you're interested, comment here with your qualifications to be the new maintainer.

/cc @CloudMailin @remo-sk

**Comment by dominicsayers** [comment]
Don't really want to be the maintainer but I will if it means getting my PR merged.

**Comment by scsmith** [comment]
We (CloudMailin) can officially maintain this if needed. I've not followed griddler in huge detail but we use a lot of Ruby so I'm sure it won't take long to catch up.

**Comment by gabebw** [comment]
@scsmith Great, who should I transfer ownership of this repo to? @CloudMailin?

**Comment by gabebw** [comment]
In the interests of convenience, @scsmith I've made you an admin so you can add whichever collaborators from CloudMailin you deem necessary.
